name: mta
description: Multi-tenant Blood Pressure Management Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  drift: ^2.29.0
  equatable: ^2.0.5
  excel: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^9.0.5
  go_router: ^17.0.0
  intl: any
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  sqlite3_flutter_libs: ^0.5.0
  timezone: ^0.10.1

dev_dependencies:
  build_runner: ^2.4.0
  drift_dev: ^2.20.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  # assets:
  #   - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
