name: mta
description: Multi-tenant Blood Pressure Management Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  android_alarm_manager_plus: ^5.0.0
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  drift: ^2.29.0
  equatable: ^2.0.7
  excel: ^4.0.6
  file_picker: ^10.3.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^19.5.0
  flutter_localizations:
    sdk: flutter
  get_it: ^9.1.1
  go_router: ^17.0.0
  intl: any
  path: ^1.9.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  sqlite3_flutter_libs: ^0.5.40
  timezone: ^0.10.1
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.10.4
  drift_dev: ^2.29.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/sounds/notification.mp3
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
